  CREATE TABLE "POWERMONITOR_DEV"."POWERMONITOR_LOG"
   (	"ID" NUMBER NOT NULL ENABLE,
	"MESSAGE" VARCHAR2(256) COLLATE "USING_NLS_COMP",
	"TYPE" VARCHAR2(20) COLLATE "USING_NLS_COMP",
	CONSTRAINT "POWERMONITOR_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) DEFAULT COLLATION "USING_NLS_COMP"  SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA";
