-- Generated by Oracle SQL Developer REST Data Services 21.4.1.349.1822
-- Exported REST Definitions from ORDS Schema Version 21.4.2.r0621806
-- Schema: POWERMONITOR_DEV   Date: Thu Mar 31 16:58:33 CEST 2022
--
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;
BEGIN
  ORDS.DEFINE_MODULE(
      p_module_name    => 'rest-v2',
      p_base_path      => '/rest-v2/',
      p_items_per_page =>  0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v2',
      p_pattern        => 'discovergy/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v2',
      p_pattern        => 'discovergy/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

INSERT INTO discovergy_rest (
    id,
    measure_time,
    energy,
    energyout,
    power,
    clientname
  ) VALUES (
    null,
    to_date(:measure_time,''YYYY-MM-DD"T"HH24:MI:SS''),
    :energy,
    :energyout,
    :power,
    :clientname
  );                       
    :status := 202;
exception when others then
    :status := 400;
    :ermesg := sqlerrm;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'rest-v2',
      p_pattern            => 'discovergy/',
      p_method             => 'POST',
      p_name               => 'ERROR_MESSAGE',
      p_bind_variable_name => 'ermesg',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'rest-v2',
      p_pattern            => 'discovergy/',
      p_method             => 'POST',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);   

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'rest-v2',
      p_pattern        => 'inverter/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'rest-v2',
      p_pattern        => 'inverter/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN

INSERT INTO inverter_rest (
    id,
    measure_time,
    inverter_type,
    actual_energie,
    daily_energie,
    total_energie
  ) VALUES (
    null,
    to_date(:measure_time,''YYYY-MM-DD"T"HH24:MI:SS''),
    :inverter_type,
    :actual_energie,
    :daily_energie,
    :total_energie
  );                       
    :status := 202;
exception when others then
    :status := 400;
    :ermesg := sqlerrm;
END;'
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'rest-v2',
      p_pattern            => 'inverter/',
      p_method             => 'POST',
      p_name               => 'ERROR_MESSAGE',
      p_bind_variable_name => 'ermesg',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'rest-v2',
      p_pattern            => 'inverter/',
      p_method             => 'POST',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);      

  ORDS.CREATE_ROLE(p_role_name  => 'discovergy_role');
  ORDS.CREATE_ROLE(p_role_name  => 'inverter_role');

  l_roles(1)   := 'discovergy_role';
  l_roles(2)   := 'inverter_role';
  l_modules(1) := 'rest-v2';
  l_patterns(1):= '/discovergy/*';
  l_patterns(2):= '/inverter/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'inverter_priv',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'Inverter_Rest Data',
      p_description    => 'Allow access to the Inverter_Rest data.',
      p_comments       => NULL);      


  COMMIT; 

END;