--------------------------------------------------------
--  DDL for Table DAILY_DISCOVERGY
--------------------------------------------------------

  CREATE TABLE "POWERMONITOR"."DAILY_DISCOVERGY" 
   (	"DAY" DATE, 
	"CLIENTNAME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"MIN_RECEIVE_COUNTER_KWH" NUMBER, 
	"MAX_RECEIVE_COUNTER_KWH" NUMBER, 
	"MIN_FEED_IN_COUNTER_KWH" NUMBER, 
	"MAX_FEED_IN_COUNTER_KWH" NUMBER, 
	"MIN_ACT_POWER_WATT" NUMBER, 
	"MAX_ACT_POWER_WATT" NUMBER, 
	"AVG_ACT_POWER_WATT" NUMBER, 
	"RECEIVE_PRICE" NUMBER, 
	"FEED_IN_PRICE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "POWERMONITOR"."DAILY_DISCOVERGY"."MIN_RECEIVE_COUNTER_KWH" IS 'kWh';
   COMMENT ON COLUMN "POWERMONITOR"."DAILY_DISCOVERGY"."MAX_RECEIVE_COUNTER_KWH" IS 'kWh';
   COMMENT ON COLUMN "POWERMONITOR"."DAILY_DISCOVERGY"."MIN_FEED_IN_COUNTER_KWH" IS 'kWh';
   COMMENT ON COLUMN "POWERMONITOR"."DAILY_DISCOVERGY"."MAX_FEED_IN_COUNTER_KWH" IS 'kWh';
   COMMENT ON COLUMN "POWERMONITOR"."DAILY_DISCOVERGY"."MIN_ACT_POWER_WATT" IS 'Watt';
   COMMENT ON COLUMN "POWERMONITOR"."DAILY_DISCOVERGY"."MAX_ACT_POWER_WATT" IS 'Watt';
   COMMENT ON COLUMN "POWERMONITOR"."DAILY_DISCOVERGY"."AVG_ACT_POWER_WATT" IS 'Watt';
   COMMENT ON COLUMN "POWERMONITOR"."DAILY_DISCOVERGY"."RECEIVE_PRICE" IS 'Euro';
   COMMENT ON COLUMN "POWERMONITOR"."DAILY_DISCOVERGY"."FEED_IN_PRICE" IS 'Euro';
--------------------------------------------------------
--  DDL for Index DAILY_DISCOVERGY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "POWERMONITOR"."DAILY_DISCOVERGY_PK" ON "POWERMONITOR"."DAILY_DISCOVERGY" ("DAY", "CLIENTNAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table DAILY_DISCOVERGY
--------------------------------------------------------

  ALTER TABLE "POWERMONITOR"."DAILY_DISCOVERGY" MODIFY ("CLIENTNAME" NOT NULL ENABLE);
  ALTER TABLE "POWERMONITOR"."DAILY_DISCOVERGY" ADD CONSTRAINT "DAILY_DISCOVERGY_PK" PRIMARY KEY ("DAY", "CLIENTNAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "POWERMONITOR"."DAILY_DISCOVERGY" MODIFY ("DAY" NOT NULL ENABLE);
