--------------------------------------------------------
--  DDL for Table HOURLY_INVERTER
--------------------------------------------------------

  CREATE TABLE "POWERMONITOR"."HOURLY_INVERTER" 
   (	"DATUM" DATE, 
	"CLIENTNAME" VARCHAR2(256 BYTE) COLLATE "USING_NLS_COMP", 
	"ACTUAL_ENERGIE" NUMBER, 
	"MAX_DAILY_ENERGIE" NUMBER, 
	"MIN_DAILY_ENERGIE" NUMBER, 
	"MAX_TOTAL_ENERGIE" NUMBER, 
	"MIN_TOTAL_ENERGIE" NUMBER, 
	"FIRST_TIME_PV_ENERGIE" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index HOURLY_INVERTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "POWERMONITOR"."HOURLY_INVERTER_PK" ON "POWERMONITOR"."HOURLY_INVERTER" ("DATUM", "CLIENTNAME") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table HOURLY_INVERTER
--------------------------------------------------------

  ALTER TABLE "POWERMONITOR"."HOURLY_INVERTER" MODIFY ("CLIENTNAME" NOT NULL ENABLE);
  ALTER TABLE "POWERMONITOR"."HOURLY_INVERTER" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "POWERMONITOR"."HOURLY_INVERTER" ADD CONSTRAINT "HOURLY_INVERTER_PK" PRIMARY KEY ("DATUM", "CLIENTNAME")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
