  CREATE TABLE "POWERMONITOR"."INVERTER_REST"
   (	"ID" NUMBER NOT NULL ENABLE,
	"MEASURE_TIME" DATE NOT NULL ENABLE,
	"ACTUAL_ENERGIE" NUMBER(8,2),
	"DAILY_ENERGIE" NUMBER(8,2),
	"TOTAL_ENERGIE" NUMBER(8,2),
	"CLIENTNAME" VARCHAR2(256) COLLATE "USING_NLS_COMP",
	CONSTRAINT "INVERTER_REST_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   ) DEFAULT COLLATION "USING_NLS_COMP"  SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA";
